---
- name: Create required dirs
  loop:
    - "{{ owncloud_volume_hooks }}"
    - "{{ owncloud_volume_hooks }}/pre_install.d"
    - "{{ owncloud_volume_hooks }}/post_install.d"
    - "{{ owncloud_volume_hooks }}/pre_server.d"
    - "{{ owncloud_volume_hooks }}/post_server.d"
    - "{{ owncloud_volume_server }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Pre install content
  loop: "{{ owncloud_pre_install | default(False) }}"
  when: item.content | default(False)
  notify:
    - Restart owncloud
  copy:
    content: "{{ item.content }}"
    dest: "{{ owncloud_volume_hooks }}/pre_install.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Pre install template
  loop: "{{ owncloud_pre_install | default(False) }}"
  when: item.path | default(False)
  notify:
    - Restart owncloud
  template:
    src: "{{ item.path }}"
    dest: "{{ owncloud_volume_hooks }}/pre_install.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Pre install remove
  loop: "{{ owncloud_pre_install | default(False) }}"
  when: item.state | default("present") == "absent"
  notify:
    - Restart owncloud
  file:
    path: "{{ owncloud_volume_hooks }}/pre_install.d/{{ item.name }}"
    state: absent
  tags:
    - owncloud

- name: Post install content
  loop: "{{ owncloud_post_install | default(False) }}"
  when: item.content | default(False)
  notify:
    - Restart owncloud
  copy:
    content: "{{ item.content }}"
    dest: "{{ owncloud_volume_hooks }}/post_install.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Post install template
  loop: "{{ owncloud_post_install | default(False) }}"
  when: item.path | default(False)
  notify:
    - Restart owncloud
  template:
    src: "{{ item.path }}"
    dest: "{{ owncloud_volume_hooks }}/post_install.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Post install remove
  loop: "{{ owncloud_post_install | default(False) }}"
  when: item.state | default("present") == "absent"
  notify:
    - Restart owncloud
  file:
    path: "{{ owncloud_volume_hooks }}/post_install.d/{{ item.name }}"
    state: absent
  tags:
    - owncloud

- name: Pre server content
  loop: "{{ owncloud_pre_server | default(False) }}"
  when: item.content | default(False)
  notify:
    - Restart owncloud
  copy:
    content: "{{ item.content }}"
    dest: "{{ owncloud_volume_hooks }}/pre_server.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Pre server template
  loop: "{{ owncloud_pre_server | default(False) }}"
  when: item.path | default(False)
  notify:
    - Restart owncloud
  template:
    src: "{{ item.path }}"
    dest: "{{ owncloud_volume_hooks }}/pre_server.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Pre server remove
  loop: "{{ owncloud_pre_server | default(False) }}"
  when: item.state | default("present") == "absent"
  notify:
    - Restart owncloud
  file:
    path: "{{ owncloud_volume_hooks }}/pre_server.d/{{ item.name }}"
    state: absent
  tags:
    - owncloud

- name: Post server content
  loop: "{{ owncloud_post_server | default(False) }}"
  when: item.content | default(False)
  notify:
    - Restart owncloud
  copy:
    content: "{{ item.content }}"
    dest: "{{ owncloud_volume_hooks }}/post_server.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Post server template
  loop: "{{ owncloud_post_server | default(False) }}"
  when: item.path | default(False)
  notify:
    - Restart owncloud
  template:
    src: "{{ item.path }}"
    dest: "{{ owncloud_volume_hooks }}/post_server.d/{{ item.name }}"
    mode: u=rwx,g=rx,o=rx
  tags:
    - owncloud

- name: Post server remove
  loop: "{{ owncloud_post_server | default(False) }}"
  when: item.state | default("present") == "absent"
  notify:
    - Restart owncloud
  file:
    path: "{{ owncloud_volume_hooks }}/post_server.d/{{ item.name }}"
    state: absent
  tags:
    - owncloud

- name: Write env config
  notify:
    - Restart owncloud
  template:
    src: default.j2
    dest: /etc/default/owncloud
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - owncloud

- name: Write service file
  notify:
    - Restart owncloud
  template:
    src: service.j2
    dest: /etc/systemd/system/owncloud.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - owncloud

- name: Pull docker image
  when:
    - owncloud_pull_image
  docker_image:
    name: "{{ owncloud_image }}"
    source: pull
  tags:
    - owncloud

- name: Create docker network
  when:
    - owncloud_network | default(False)
  docker_network:
    name: '{{ owncloud_network }}'
  tags:
    - owncloud

- name: Start owncloud service
  systemd:
    name: owncloud
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - owncloud

...
